### ISSUE TITLE
Problem with PAPI & Vault

### ISSUE THREAD

**Issue by MutantPiggieGolem1** [axelrindle/SimpleCoins#2]
The error below comes up because SimpleCoins, PlaceholderAPI, and Vault are having a problem with each other. How can I fix this without removing any plugins?

Info:
Plugins: LuckPerms, CustomDeathMessages, WorldEdit, OpenInv, PlaceholderAPI, ArmorStandEditor, EasyWarp, ServerRestorer, Vault, Multiverse-Core, WorldGuard, ProtocolLib, LuckPermsChat, VanishNoPacket, Scoreboard-revision, Multiverse-Inventories, PwnFilter, Multiverse-Portals, HolographicDisplays, SimpleCoins, AParkour, Multiverse-NetherPortals
Server Version: Spigot 1.14.4 (git-Spigot-cbd1a1b-009d8af)
OS:
```
Linux [computername] 5.0.0-38-generic #41-Ubuntu SMP Tue Dec 3 00:27:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-0ubuntu1.119.04)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Ubuntu-0ubuntu1.119.04, mixed mode, sharing)
```
The Error:
```
[11:45:49] [Craft Scheduler Thread - 5/WARN]: [PlaceholderAPI] Plugin PlaceholderAPI v2.10.6 generated an exception while executing task 64
java.lang.NullPointerException: null
        at de.lalo5.simplecoins.CoinManager.getCoins(CoinManager.java:92) ~[?:?]
        at de.lalo5.simplecoins.CoinManager.getCoins(CoinManager.java:79) ~[?:?]
        at de.lalo5.simplecoins.CoinManager$SimpleEconomy.getBalance(CoinManager.java:350) ~[?:?]
        at com.extendedclip.papi.expansion.vault.VaultEcoHook.getBalance(VaultEcoHook.java:220) ~[?:?]
        at com.extendedclip.papi.expansion.vault.BalTopTask.run(BalTopTask.java:48) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by axelrindle** [comment]
I assume you're using `v0.4` of SimpleCoins.

The `NullPointerException` occurs in the file `CoinManager.java` in line 92. When looking into the [source code](https://github.com/axelrindle/SimpleCoins/blob/v0.4/src/main/java/de/lalo5/simplecoins/CoinManager.java#L92), this is the line:

```java
String uuid = player.getUniqueId().toString();
```

The `player` is the parameter to the method `getCoins`. It seems like the `PlaceholderAPI` passes a `null` value to it.

**Comment by MutantPiggieGolem1** [comment]
I really need this plugin, and it fits my server perfectly. Is there a way this could be fixed?
As I said, I really like this plugin.

**Comment by axelrindle** [comment]
Your problem originates from the plugin `PlaceholderAPI`. As I said, it passes a `null` value to the method, from which no data can be read.

You should probably open an issue on [their repository](https://github.com/PlaceholderAPI/PlaceholderAPI), as the only thing I can do is check for null values in the code, which does not resolve your issue.

Otherwise it might be helpful to share the part of your configuration, which is responsible for accessing a Player's balance.
